# Pytorch Fundamentals

## Introduction to Tensors

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.1


### Creating Tensors

A **tensor** is a fundamental data structure in PyTorch, generalizing scalars, vectors, and matrices to potentially higher dimensions. 

#### **1. Intuitive Understanding**

- **Scalar**: A single number (0D tensor), e.g., temperature = 37°C.
- **Vector**: An array of numbers (1D tensor), e.g., [height, weight, age].
- **Matrix**: A 2D array (2D tensor), e.g., grayscale image pixels.
- **Tensor**: An n-dimensional array (nD tensor), e.g., color images (3D), video (4D), or batches of data.

**Analogy:**  
Think of a tensor as a general container for data, like a spreadsheet (matrix), but extended to more dimensions—imagine a stack of spreadsheets (3D), or a sequence of such stacks (4D).

#### **2. Mathematical Foundation**

A tensor is a multi-dimensional array of numerical values. Formally, an n-th order tensor is an element of the tensor product of n vector spaces.

- **Order (Rank):** Number of dimensions (axes).
- **Shape:** Size along each dimension.

**Example:**  
A tensor of shape (3, 4, 5) is a 3D tensor with 3 matrices, each of size 4x5.


**In PyTorch:**  
Tensors are implemented as contiguous blocks of memory, supporting efficient computation and broadcasting.


#### **4. Key Operations**

- **Reshaping:** `tensor.view()`, `tensor.reshape()`
- **Indexing/Slicing:** `tensor[0]`, `tensor[:, 1]`
- **Mathematical Ops:** `torch.add()`, `torch.matmul()`, etc.
- **Broadcasting:** Automatic expansion of dimensions for operations.

#### **5. Real-World Analogies**

- **Images:** 2D (grayscale) or 3D (color) tensors.
- **Videos:** 4D tensors (batch, channel, height, width).
- **Text:** 2D or 3D tensors (batch, sequence length, embedding size).

#### **6. Applications in AI/ML**

- **Deep Learning:** All neural network computations (inputs, weights, activations) are tensor operations.
- **Computer Vision:** Images and videos as tensors.
- **Natural Language Processing:** Sentences as sequences of word embeddings (tensors).
- **Reinforcement Learning:** States, actions, and rewards as tensors.

#### **7. Why Tensors?**

- **Efficiency:** Optimized for GPU/TPU computation.
- **Flexibility:** Can represent any data structure needed for ML.
- **Expressiveness:** Enable complex operations (convolutions, matrix multiplications) essential for modern AI.

In [3]:
# scalar
# creating pytorch tensor using torch.Tensor()
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim  # number of dimensions

0

In [5]:
scalar.item()  # get the value of the tensor

7

### Creating Vectors


#### Intuitive Understanding

A **vector** is a one-dimensional array of numbers. In PyTorch, a vector is represented as a 1D tensor. Vectors are fundamental in mathematics, physics, and machine learning, serving as the building blocks for more complex structures.

- **Example:**  
    `vector = torch.tensor([7, 7])`  
    This is a 1D tensor (vector) with two elements.

**Intuition:**  
Think of a vector as an arrow in space, defined by its direction and magnitude. In data science, vectors often represent features of a data point (e.g., height and weight of a person).

####  Why Vectors Matter in PyTorch

- **Efficiency:** PyTorch operations are vectorized for speed, leveraging GPUs.
- **Expressiveness:** Vectors enable concise representation of data and parameters.
- **Foundation:** All higher-dimensional tensors (matrices, etc.) are built from vectors.



In [6]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim  # number of dimensions

1

In [8]:
vector.shape  # shape of the tensor

torch.Size([2])

In [9]:
# MATRIX
matrix = torch.tensor([[7, 8], [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
matrix.ndim  # number of dimensions

2

In [11]:
matrix[1]

tensor([ 9, 10])

In [12]:
matrix.shape  # shape of the tensor

torch.Size([2, 2])

In [13]:
# TENSOR    
TENSOR = torch.tensor([[[1, 2, 3], 
                        [4,5,6,],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim  # number of dimensions

3

In [15]:
TENSOR.shape  # shape of the tensor

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensors

Random tensors are tensors whose values are sampled from a probability distribution, such as uniform or normal (Gaussian) distributions. In PyTorch, we can create random tensors using functions like `torch.rand()`, `torch.randn()`, and `torch.randint()`.

**Why use random tensors?**

- **Weight Initialization:** Neural networks require their weights to be initialized randomly to break symmetry and help the model learn effectively.
- **Simulating Data:** Random tensors are useful for testing models and functions when real data is unavailable.
- **Stochastic Processes:** Many machine learning algorithms rely on randomness, such as dropout or data augmentation.

Random tensors are essential for reproducibility and experimentation in deep learning workflows.

In [17]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6302, 0.6862, 0.9757, 0.1322],
        [0.8712, 0.7826, 0.6550, 0.8772],
        [0.9447, 0.0691, 0.4804, 0.0456]])

In [18]:
random_tensor.ndim  # number of dimensions

2

In [19]:
# Creating a random tensor with specific shape of an image tensor
random_image_size_tensor = torch.rand(size = (224,224, 3)) # 3 color channels, 224 height, 224 width and rgb color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim # shape and dimension of the tensor

(torch.Size([224, 224, 3]), 3)