# Pytorch Fundamentals

## Introduction to Tensors

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.1


### Creating Tensors

A **tensor** is a fundamental data structure in PyTorch, generalizing scalars, vectors, and matrices to potentially higher dimensions. 

#### **1. Intuitive Understanding**

- **Scalar**: A single number (0D tensor), e.g., temperature = 37°C.
- **Vector**: An array of numbers (1D tensor), e.g., [height, weight, age].
- **Matrix**: A 2D array (2D tensor), e.g., grayscale image pixels.
- **Tensor**: An n-dimensional array (nD tensor), e.g., color images (3D), video (4D), or batches of data.

**Analogy:**  
Think of a tensor as a general container for data, like a spreadsheet (matrix), but extended to more dimensions—imagine a stack of spreadsheets (3D), or a sequence of such stacks (4D).

#### **2. Mathematical Foundation**

A tensor is a multi-dimensional array of numerical values. Formally, an n-th order tensor is an element of the tensor product of n vector spaces.

- **Order (Rank):** Number of dimensions (axes).
- **Shape:** Size along each dimension.

**Example:**  
A tensor of shape (3, 4, 5) is a 3D tensor with 3 matrices, each of size 4x5.


**In PyTorch:**  
Tensors are implemented as contiguous blocks of memory, supporting efficient computation and broadcasting.


#### **4. Key Operations**

- **Reshaping:** `tensor.view()`, `tensor.reshape()`
- **Indexing/Slicing:** `tensor[0]`, `tensor[:, 1]`
- **Mathematical Ops:** `torch.add()`, `torch.matmul()`, etc.
- **Broadcasting:** Automatic expansion of dimensions for operations.

#### **5. Real-World Analogies**

- **Images:** 2D (grayscale) or 3D (color) tensors.
- **Videos:** 4D tensors (batch, channel, height, width).
- **Text:** 2D or 3D tensors (batch, sequence length, embedding size).

#### **6. Applications in AI/ML**

- **Deep Learning:** All neural network computations (inputs, weights, activations) are tensor operations.
- **Computer Vision:** Images and videos as tensors.
- **Natural Language Processing:** Sentences as sequences of word embeddings (tensors).
- **Reinforcement Learning:** States, actions, and rewards as tensors.

#### **7. Why Tensors?**

- **Efficiency:** Optimized for GPU/TPU computation.
- **Flexibility:** Can represent any data structure needed for ML.
- **Expressiveness:** Enable complex operations (convolutions, matrix multiplications) essential for modern AI.

In [2]:
# scalar
# creating pytorch tensor using torch.Tensor()
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim  # number of dimensions

0

In [4]:
scalar.item()  # get the value of the tensor

7

### Creating Vectors


#### Intuitive Understanding

A **vector** is a one-dimensional array of numbers. In PyTorch, a vector is represented as a 1D tensor. Vectors are fundamental in mathematics, physics, and machine learning, serving as the building blocks for more complex structures.

- **Example:**  
    `vector = torch.tensor([7, 7])`  
    This is a 1D tensor (vector) with two elements.

**Intuition:**  
Think of a vector as an arrow in space, defined by its direction and magnitude. In data science, vectors often represent features of a data point (e.g., height and weight of a person).

####  Why Vectors Matter in PyTorch

- **Efficiency:** PyTorch operations are vectorized for speed, leveraging GPUs.
- **Expressiveness:** Vectors enable concise representation of data and parameters.
- **Foundation:** All higher-dimensional tensors (matrices, etc.) are built from vectors.



In [5]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim  # number of dimensions

1

In [7]:
vector.shape  # shape of the tensor

torch.Size([2])

In [8]:
# MATRIX
matrix = torch.tensor([[7, 8], [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
matrix.ndim  # number of dimensions

2

In [10]:
matrix[1]

tensor([ 9, 10])

In [11]:
matrix.shape  # shape of the tensor

torch.Size([2, 2])

In [12]:
# TENSOR    
TENSOR = torch.tensor([[[1, 2, 3], 
                        [4,5,6,],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim  # number of dimensions

3

In [14]:
TENSOR.shape  # shape of the tensor

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensors

Random tensors are tensors whose values are sampled from a probability distribution, such as uniform or normal (Gaussian) distributions. In PyTorch, we can create random tensors using functions like `torch.rand()`, `torch.randn()`, and `torch.randint()`.

**Why use random tensors?**

- **Weight Initialization:** Neural networks require their weights to be initialized randomly to break symmetry and help the model learn effectively.
- **Simulating Data:** Random tensors are useful for testing models and functions when real data is unavailable.
- **Stochastic Processes:** Many machine learning algorithms rely on randomness, such as dropout or data augmentation.

Random tensors are essential for reproducibility and experimentation in deep learning workflows.

In [16]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.0953, 0.4583, 0.2522, 0.4809],
        [0.2706, 0.8970, 0.5260, 0.6321],
        [0.9633, 0.6385, 0.0459, 0.1848]])

In [17]:
random_tensor.ndim  # number of dimensions

2

In [18]:
# Creating a random tensor with specific shape of an image tensor
random_image_size_tensor = torch.rand(size = (224,224, 3)) # 3 color channels, 224 height, 224 width and rgb color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim # shape and dimension of the tensor

(torch.Size([224, 224, 3]), 3)

### Tensors of Zeros and Ones

In [19]:
# Creating a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
# creating a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a Range of Tensors and Tensors-Like

In [21]:
# Using torch.arange() to create a tensor of a range of numbers
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
#  one to thousand with step of 50
one_to_thousand = torch.arange(1, 1001, 50)
one_to_thousand

tensor([  1,  51, 101, 151, 201, 251, 301, 351, 401, 451, 501, 551, 601, 651,
        701, 751, 801, 851, 901, 951])

In [23]:
# Creating tensors like
thousand_zeros = torch.zeros_like(input=one_to_thousand)
thousand_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [24]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float32)
float_32_tensor

tensor([3., 6., 9.])

A **tensor datatype** (or `dtype`) specifies the kind of elements contained in a tensor, such as integers, floating-point numbers, or booleans. The datatype determines how much memory each element uses and what operations are supported.

#### Common PyTorch Tensor Datatypes

| PyTorch dtype         | Description                | Example usage                |
|---------------------- |---------------------------|------------------------------|
| `torch.float32`       | 32-bit floating point      | Neural network weights       |
| `torch.float64`       | 64-bit floating point      | High-precision calculations  |
| `torch.int32`         | 32-bit integer             | Indexing, counting           |
| `torch.int64`         | 64-bit integer (long)      | Large indices, counters      |
| `torch.bool`          | Boolean (True/False)       | Masks, conditions            |

We can specify the dtype when creating a tensor:
```python
float_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
int_tensor = torch.tensor([1, 2, 3], dtype=torch.int64)
```

#### Why Tensor Datatypes Matter

- **Memory Usage:** Lower precision (e.g., `float16`) uses less memory, allowing larger models or batches.
- **Computation Speed:** Some hardware (like GPUs/TPUs) is optimized for specific datatypes.
- **Numerical Precision:** Higher precision (e.g., `float64`) reduces rounding errors but is slower and uses more memory.

#### Problems That Arise with Tensor Datatypes

1. **Type Mismatch Errors:**  
    Operations between tensors of different dtypes can cause errors or unexpected results.
    ```python
    a = torch.tensor([1.0, 2.0], dtype=torch.float32)
    b = torch.tensor([1, 2], dtype=torch.int32)
    # a + b will raise a RuntimeError unless dtypes are matched
    ```

2. **Loss of Precision:**  
    Converting from higher to lower precision (e.g., `float64` to `float32`) can lose information.
    ```python
    high_precision = torch.tensor([1.123456789], dtype=torch.float64)
    low_precision = high_precision.to(torch.float32)
    # low_precision may not store all decimal places
    ```

3. **Increased Memory Usage:**  
    Using unnecessarily high precision (e.g., `float64` for images) wastes memory and slows down computation.

4. **Incompatible Operations:**  
    Some operations require specific dtypes (e.g., indices must be `int64` for advanced indexing).

#### Best Practices

- Use `float32` for most deep learning tasks (default in PyTorch).
- Use integer types for labels, indices, or counting.
- Be explicit about dtypes when precision or compatibility matters.
- Convert dtypes using `.to()`, `.float()`, `.long()`, etc.

**Example:**
```python
tensor = torch.arange(10)           # Default dtype: int64
tensor = tensor.float()             # Convert to float32
```

Understanding and managing tensor datatypes is crucial for efficient, correct, and reproducible deep learning workflows.