# Matrix Multiplication and Eigen Computations


Here we are computing Eigen Values and Eigen Vectors of a Real Matrix
- Power Method
- Variations of Power Method (Inverse, Shifted)
- QR Method

## Power Method

See [Wikipedia article on Power Iteration](https://en.wikipedia.org/wiki/Power_iteration): 

- $A$ : $n \times n$ real matrix.
- Assumptions:
  1. $A$ has a full set of eigenvalues $\lambda_1, \lambda_2, \ldots, \lambda_n$.
  2. $|\lambda_1| > |\lambda_2| \geq |\lambda_i|, 3 \leq i \leq n$

**Power Iteration:**

1. Pick an arbitary unit vector $v_0 \in \mathbb R^n$
2. Repeat the iteration $v_{t+1} = \frac{Av_t}{\lVert Av_t \lVert}$ till it converges

Once it converges, $v_t$ is very close to the eigenvector of $A$ corresponding to the eigenvalue $\lambda_1$

*Rate of convergence:* $\frac{|\lambda_2|}{|\lambda_1|}$.

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Write the power iteration function

def power_iteration(A, num_iterations=20):
    v = np.random.rand(A.shape[1])
    for t in range(num_iterations):
        u = A @ v  # np.matmul(A, v)
        v = u / np.linalg.norm(u)

    l = v.T @ (A @ v)
    return v, l

# Power Iteration function which starts from a given vector


def power_iteration_seed(A, v0, num_iterations=20):
    v = v0
    for t in range(num_iterations):
        u = A @ v
        v = u / np.linalg.norm(u)

    l = v.T @ (A @ v)
    return v, l

In [3]:
# Use power iteration to compute the largest eigenvalue of a matrix
# and compare it with the result using np.linalg.eig()

A = np.array([[0.5, 0.5], [0.2, 0.8]])
print(A)
v1, l1 = power_iteration(A)

print(f'Eigenvalue with largest magnitude: {l1:.4f}')
print('Corresponding Eigenvector:', v1)

# Compare with result from np.linalg.eig()
E, V = np.linalg.eig(A)
print("Eigenvalues:\n", E)
print("Eigenvectors: \n", V)

[[0.5 0.5]
 [0.2 0.8]]
Eigenvalue with largest magnitude: 1.0000
Corresponding Eigenvector: [0.70710678 0.70710678]
Eigenvalues:
 [0.3 1. ]
Eigenvectors: 
 [[-0.92847669 -0.70710678]
 [ 0.37139068 -0.70710678]]


In [4]:
# When can power iteration go wrong
v0 = V[:, 0].T
v1, l1 = power_iteration_seed(A, v0)

print(f'Eigenvalue with largest magnitude: {l1:.4f}')
print('Corresponding Eigenvector:', v1)

Eigenvalue with largest magnitude: 0.3000
Corresponding Eigenvector: [-0.92847615  0.37139203]


### In Case if Power Method Fails

In [5]:
# More than one eigenvalue with the largest magnitude

th = np.pi/6
A = np.array([[0.5, 0, 0], [0, np.cos(th), -np.sin(th)],
             [0, np.sin(th), np.cos(th)]])
print(A)

v1, l1 = power_iteration(A)

print(f'Eigenvalue with largest magnitude: {l1:.4f}')
print('Corresponding Eigenvector:', v1)

# Compare with result from np.linalg.eig()
E, V = np.linalg.eig(A)
print("Eigenvalues:\n", E)
print("Eigenvectors: \n", V)

[[ 0.5        0.         0.       ]
 [ 0.         0.8660254 -0.5      ]
 [ 0.         0.5        0.8660254]]
Eigenvalue with largest magnitude: 0.8660
Corresponding Eigenvector: [ 3.69862736e-07  5.54655913e-01 -8.32079815e-01]
Eigenvalues:
 [0.8660254+0.5j 0.8660254-0.5j 0.5      +0.j ]
Eigenvectors: 
 [[0.        +0.j         0.        -0.j         1.        +0.j        ]
 [0.        +0.70710678j 0.        -0.70710678j 0.        +0.j        ]
 [0.70710678+0.j         0.70710678-0.j         0.        +0.j        ]]


### Convergence of Power Iteration